server:
  port: 8123
  servlet:
    context-path: /api
spring:
  application:
    name: lz-picture-backend
    #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lz_picture
    username: root
    password: 123456
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    #仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
      db-config:
        logic-delete-field: isDelete #全局逻辑删除的实体字段名
        logic-delete-value: 1  # 逻辑删除值 （默认为1）
        logic-not-delete-value: 0  # 逻辑未删除值 （默认为0）
#接口文档配置
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      # 添加默认分组，这样访问 /api/v2/api-docs 不需要 group 参数
      default:
        api-rule: package
        api-rule-resources:
          - com.lz.lzpicturebackend.controller
      test1:
        api-rule: package
        api-rule-resources:
          - com.lz.lzpicturebackend.controller

